FROM microsoft/aspnetcore-build:latest AS build

WORKDIR /code

COPY Wikiled.Postal.Web .
RUN dotnet publish --output /output --configuration Release

FROM microsoft/aspnetcore:latest

COPY --from=build /output /app

WORKDIR /app

ENTRYPOINT [ "dotnet", "Wikiled.Postal.Web.dll" ]