FROM microsoft/aspnetcore-build:latest AS builder
WORKDIR /source

COPY *.csproj .
RUN dotnet restore

# copies the rest of your code
COPY . .
RUN dotnet publish --output /app/ --configuration Release

# Stage 2
FROM microsoft/aspnetcore:latest
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["dotnet", "Wikiled.Postal.Web.dll"]

