FROM microsoft/aspnetcore-build:2.0.0 AS build

WORKDIR /code

COPY Wikiled.Postal.Web .

RUN dotnet restore
RUN dotnet build
RUN npm install \ 
	&& npm install -g @angular/cli \
	&& npm run build:prod	

RUN dotnet publish --output /output --configuration Release

FROM microsoft/aspnetcore:2.0.0

COPY --from=build /output /app

WORKDIR /app

ENTRYPOINT [ "dotnet", "Wikiled.Postal.Web.dll" ]