version: '3.4'

services:
  ci-build:
    image: wikiled.postal.web
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Wikiled.Postal.Web.sln && dotnet publish ./Wikiled.Postal.Web.sln -c Release -o ./obj/Docker/publish"